export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP";
export const SET_SHOW_GROUP_MENU = "SET_SHOW_GROUP_MENU";
export const SET_SHOW_ADD_CRED = "SET_SHOW_ADD_CRED";
export const SET_THEME = "SET_THEME";
export const SET_DND_CRED = "SET_DND_CRED";
